# Generated by Django 4.1.3 on 2022-12-05 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
                ('show_on_home', models.BooleanField()),
                ('order', models.IntegerField(null=True)),
            ],
        ),
    ]
